# Generated by Django 6.0.5 on 2026-05-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(editable=False, max_length=6, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("municipio", models.CharField(max_length=120)),
                ("departamento", models.CharField(max_length=120)),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField()),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rubro", models.CharField(max_length=120)),
                ("presupuesto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="organizaciones.proyecto",
                    ),
                ),
            ],
            options={
                "ordering": ["proyecto__codigo", "rubro"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proyecto", "rubro"),
                        name="unique_presupuesto_rubro_por_proyecto",
                    )
                ],
            },
        ),
    ]
