# Generated by Django 6.0.5 on 2026-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="departamento",
            field=models.CharField(
                choices=[
                    ("Alta Verapaz", "Alta Verapaz"),
                    ("Baja Verapaz", "Baja Verapaz"),
                    ("Chimaltenango", "Chimaltenango"),
                    ("Chiquimula", "Chiquimula"),
                    ("Guatemala", "Guatemala"),
                    ("El Progreso", "El Progreso"),
                    ("Escuintla", "Escuintla"),
                    ("Huehuetenango", "Huehuetenango"),
                    ("Izabal", "Izabal"),
                    ("Jalapa", "Jalapa"),
                    ("Jutiapa", "Jutiapa"),
                    ("Petén", "Petén"),
                    ("Quetzaltenango", "Quetzaltenango"),
                    ("Quiché", "Quiché"),
                    ("Retalhuleu", "Retalhuleu"),
                    ("Sacatepéquez", "Sacatepéquez"),
                    ("San Marcos", "San Marcos"),
                    ("Santa Rosa", "Santa Rosa"),
                    ("Sololá", "Sololá"),
                    ("Suchitepéquez", "Suchitepéquez"),
                    ("Totonicapán", "Totonicapán"),
                    ("Zacapa", "Zacapa"),
                ],
                max_length=120,
            ),
        ),
    ]
