# Generated by Django 6.0.5 on 2026-05-11 20:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0002_alter_proyecto_departamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("donante", models.CharField(max_length=200)),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donaciones",
                        to="organizaciones.presupuesto",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donaciones",
                        to="organizaciones.proyecto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "donante"],
            },
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("proveedor", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_compra",
                        to="organizaciones.proyecto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "proveedor"],
            },
        ),
        migrations.CreateModel(
            name="LineaOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas_orden_compra",
                        to="organizaciones.presupuesto",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="organizaciones.ordencompra",
                    ),
                ),
            ],
            options={
                "ordering": ["presupuesto__rubro"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("orden_compra", "presupuesto"),
                        name="unique_presupuesto_por_orden_compra",
                    )
                ],
            },
        ),
    ]
