""" Valores que no cambian """


DEPARTAMENTOS_GUATEMALA = [
    ("Alta Verapaz", "Alta Verapaz"),
    ("Baja Verapaz", "Baja Verapaz"),
    ("Chimaltenango", "Chimaltenango"),
    ("Chiquimula", "Chiquimula"),
    ("Guatemala", "Guatemala"),
    ("El Progreso", "El Progreso"),
    ("Escuintla", "Escuintla"),
    ("Huehuetenango", "Huehuetenango"),
    ("Izabal", "Izabal"),
    ("Jalapa", "Jalapa"),
    ("Jutiapa", "Jutiapa"),
    ("Petén", "Petén"),
    ("Quetzaltenango", "Quetzaltenango"),
    ("Quiché", "Quiché"),
    ("Retalhuleu", "Retalhuleu"),
    ("Sacatepéquez", "Sacatepéquez"),
    ("San Marcos", "San Marcos"),
    ("Santa Rosa", "Santa Rosa"),
    ("Sololá", "Sololá"),
    ("Suchitepéquez", "Suchitepéquez"),
    ("Totonicapán", "Totonicapán"),
    ("Zacapa", "Zacapa"),
]


MUNICIPIOS_POR_DEPARTAMENTO = {
    "Alta Verapaz": [
        "Cobán",
        "Santa Cruz Verapaz",
        "San Cristóbal Verapaz",
        "Tactic",
        "Tamahú",
        "San Miguel Tucurú",
        "Panzós",
        "Senahú",
        "San Pedro Carchá",
        "San Juan Chamelco",
        "San Agustín Lanquín",
        "Santa María Cahabón",
        "Chisec",
        "Chahal",
        "Fray Bartolomé de las Casas",
        "Santa Catalina La Tinta",
        "Raxruhá",
    ],
    "Baja Verapaz": [
        "Salamá",
        "San Miguel Chicaj",
        "Rabinal",
        "Cubulco",
        "Granados",
        "Santa Cruz el Chol",
        "San Jerónimo",
        "Purulhá",
    ],
    "Chimaltenango": [
        "Chimaltenango",
        "San José Poaquil",
        "San Martín Jilotepeque",
        "San Juan Comalapa",
        "Santa Apolonia",
        "Tecpán",
        "Patzún",
        "San Miguel Pochuta",
        "Patzicía",
        "Santa Cruz Balanyá",
        "Acatenango",
        "San Pedro Yepocapa",
        "San Andrés Itzapa",
        "Parramos",
        "Zaragoza",
        "El Tejar",
    ],
    "Chiquimula": [
        "Chiquimula",
        "Jocotán",
        "Esquipulas",
        "Camotán",
        "Quezaltepeque",
        "Olopa",
        "Ipala",
        "San Juan Ermita",
        "Concepción Las Minas",
        "San Jacinto",
        "San José la Arada",
    ],
    "Guatemala": [
        "Santa Catarina Pinula",
        "San José Pinula",
        "Guatemala",
        "San José del Golfo",
        "Palencia",
        "Chinautla",
        "San Pedro Ayampuc",
        "Mixco",
        "San Pedro Sacatapéquez",
        "San Juan Sacatepéquez",
        "Chuarrancho",
        "San Raymundo",
        "Fraijanes",
        "Amatitlán",
        "Villa Nueva",
        "Villa Canales",
        "San Miguel Petapa",
    ],
    "El Progreso": [
        "El Jícaro",
        "Morazán",
        "San Agustín Acasaguastlán",
        "San Antonio La Paz",
        "San Cristóbal Acasaguastlán",
        "Sanarate",
        "Guastatoya",
        "Sansare",
    ],
    "Escuintla": [
        "Escuintla",
        "Santa Lucía Cotzumalguapa",
        "La Democracia",
        "Siquinalá",
        "Masagua",
        "Tiquisate",
        "La Gomera",
        "Guanagazapa",
        "San José",
        "Iztapa",
        "Palín",
        "San Vicente Pacaya",
        "Nueva Concepción",
    ],
    "Huehuetenango": [
        "Huehuetenango",
        "Chiantla",
        "Malacatancito",
        "Cuilco",
        "Nentón",
        "San Pedro Necta",
        "Jacaltenango",
        "Soloma",
        "Ixtahuacán",
        "Santa Bárbara",
        "La Libertad",
        "La Democracia",
        "San Miguel Acatán",
        "San Rafael La Independencia",
        "Todos Santos Cuchumatán",
        "San Juan Atitlán",
        "Santa Eulalia",
        "San Mateo Ixtatán",
        "Colotenango",
        "San Sebastián Huehuetenango",
        "Tectitán",
        "Concepción Huista",
        "San Juan Ixcoy",
        "San Antonio Huista",
        "Santa Cruz Barillas",
        "San Sebastián Coatán",
        "Aguacatán",
        "San Rafael Petzal",
        "San Gaspar Ixchil",
        "Santiago Chimaltenango",
        "Santa Ana Huista",
        "Petatán",
    ],
    "Izabal": [
        "Morales",
        "Los Amates",
        "Livingston",
        "El Estor",
        "Puerto Barrios",
    ],
    "Jalapa": [
        "Jalapa",
        "San Pedro Pinula",
        "San Luis Jilotepeque",
        "San Manuel Chaparrón",
        "San Carlos Alzatate",
        "Monjas",
        "Mataquescuintla",
    ],
    "Jutiapa": [
        "Jutiapa",
        "El Progreso",
        "Santa Catarina Mita",
        "Agua Blanca",
        "Asunción Mita",
        "Yupiltepeque",
        "Atescatempa",
        "Jerez",
        "El Adelanto",
        "Zapotitlán",
        "Comapa",
        "Jalpatagua",
        "Conguaco",
        "Moyuta",
        "Pasaco",
        "Quesada",
    ],
    "Petén": [
        "Flores",
        "San José",
        "San Benito",
        "San Andrés",
        "La Libertad",
        "San Francisco",
        "Santa Ana",
        "Dolores",
        "San Luis",
        "Sayaxché",
        "Melchor de Mencos",
        "Poptún",
        "El Chal",
        "Las Cruces",
    ],
    "Quetzaltenango": [
        "Quetzaltenango",
        "Salcajá",
        "San Juan Olintepeque",
        "San Carlos Sija",
        "Sibilia",
        "Cabricán",
        "Cajolá",
        "San Miguel Siguilá",
        "San Juan Ostuncalco",
        "San Mateo",
        "Concepción Chiquirichapa",
        "San Martín Sacatepéquez",
        "Almolonga",
        "Cantel",
        "Huitán",
        "Zunil",
        "Colomba Costa Cuca",
        "San Francisco La Unión",
        "El Palmar",
        "Coatepeque",
        "Génova",
        "Flores Costa Cuca",
        "La Esperanza",
        "Palestina de Los Altos",
    ],
    "Quiché": [
        "Santa Cruz del Quiché",
        "Chiché",
        "Chinique",
        "Zacualpa",
        "Chajul",
        "Santo Tomás Chichicastenango",
        "Patzité",
        "San Antonio Ilotenango",
        "San Pedro Jocopilas",
        "Cunén",
        "San Juan Cotzal",
        "Santa María Joyabaj",
        "Santa María Nebaj",
        "San Andrés Sajcabajá",
        "Uspantán",
        "Sacapulas",
        "San Bartolomé Jocotenango",
        "Canillá",
        "Chicamán",
        "Ixcán",
        "Pachalum",
    ],
    "Retalhuleu": [
        "Retalhuleu",
        "San Sebastián",
        "Santa Cruz Muluá",
        "San Martín Zapotitlán",
        "San Felipe",
        "San Andrés Villa Seca",
        "Champerico",
        "Nuevo San Carlos",
        "El Asintal",
    ],
    "Sacatepéquez": [
        "Antigua Guatemala",
        "Jocotenango",
        "Pastores",
        "Sumpango",
        "Santo Domingo Xenacoj",
        "Santiago Sacatepéquez",
        "San Bartolomé Milpas Altas",
        "San Lucas Sacatepéquez",
        "Santa Lucía Milpas Altas",
        "Magdalena Milpas Altas",
        "Santa María de Jesús",
        "Ciudad Vieja",
        "San Miguel Dueñas",
        "San Juan Alotenango",
        "San Antonio Aguas Calientes",
        "Santa Catarina Barahona",
    ],
    "San Marcos": [
        "San Marcos",
        "Ayutla",
        "Catarina",
        "Comitancillo",
        "Concepción Tutuapa",
        "El Quetzal",
        "El Rodeo",
        "El Tumblador",
        "Ixchiguán",
        "La Reforma",
        "Malacatán",
        "Nuevo Progreso",
        "Ocós",
        "Pajapita",
        "Esquipulas Palo Gordo",
        "San Antonio Sacatepéquez",
        "San Cristóbal Cucho",
        "San José Ojetenam",
        "San Lorenzo",
        "San Miguel Ixtahuacán",
        "San Pablo",
        "San Pedro Sacatepéquez",
        "San Rafael Pie de la Cuesta",
        "Sibinal",
        "Sipacapa",
        "Tacaná",
        "Tajumulco",
        "Tejutla",
        "Río Blanco",
        "La Blanca",
    ],
    "Santa Rosa": [
        "Cuilapa",
        "Casillas Santa Rosa",
        "Chiquimulilla",
        "Guazacapán",
        "Nueva Santa Rosa",
        "Oratorio",
        "Pueblo Nuevo Viñas",
        "San Juan Tecuaco",
        "San Rafael Las Flores",
        "Santa Cruz Naranjo",
        "Santa María Ixhuatán",
        "Santa Rosa de Lima",
        "Taxisco",
        "Barberena",
    ],
    "Sololá": [
        "Sololá",
        "Concepción",
        "Nahualá",
        "Panajachel",
        "San Andrés Semetabaj",
        "San Antonio Palopó",
        "San José Chacayá",
        "San Juan La Laguna",
        "San Lucas Tolimán",
        "San Marcos La Laguna",
        "San Pablo La Laguna",
        "San Pedro La Laguna",
        "Santa Catarina Ixtahuacán",
        "Santa Catarina Palopó",
        "Santa Clara La Laguna",
        "Santa Cruz La Laguna",
        "Santa Lucía Utatlán",
        "Santa María Visitación",
        "Santiago Atitlán",
    ],
    "Suchitepéquez": [
        "Mazatenango",
        "Cuyotenango",
        "San Francisco Zapotitlán",
        "San Bernardino",
        "San José El Ídolo",
        "Santo Domingo Suchitépequez",
        "San Lorenzo",
        "Samayac",
        "San Pablo Jocopilas",
        "San Antonio Suchitépequez",
        "San Miguel Panán",
        "San Gabriel",
        "Chicacao",
        "Patulul",
        "Santa Bárbara",
        "San Juan Bautista",
        "Santo Tomás La Unión",
        "Zunilito",
        "Pueblo Nuevo",
        "Río Bravo",
        "San José La Máquina",
    ],
    "Totonicapán": [
        "Totonicapán",
        "San Cristóbal Totonicapán",
        "San Francisco El Alto",
        "San Andrés Xecul",
        "Momostenango",
        "Santa María Chiquimula",
        "Santa Lucía La Reforma",
        "San Bartolo Aguas Calientes",
    ],
    "Zacapa": [
        "Cabañas",
        "Estanzuela",
        "Gualán",
        "Huité",
        "La Unión",
        "Río Hondo",
        "San Jorge",
        "San Diego",
        "Teculután",
        "Usumatlán",
        "Zacapa",
    ],
}
